app/__init__.py
from flask import Flask
from config import Config


def create_app(config_class=Config) : 
    app = Flask(__name__)
    app.config.from_object(config_class)

    #Register blue print
    from app.main import bp as main_bp
    app.register_blueprint(main_bp)

    from app.posts import bp as post_bp
    app.register_blueprint(post_bp, url_prefix = '/posts')
    
    @app.route('/test')
    def test_page():
        return "test"
    
    return app 

app/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__)


from app.main import routes
    

app/main/routes.py
from app.main import bp
from flask import render_template

@bp.route('/')
def index() :
    return render_template('index.html')

app/posts/__init__.py
from flask import Blueprint

bp = Blueprint('posts', __name__)

from app.posts import routes

app/posts/routes.py
from  app.posts import bp
from flask import render_template

@bp.route("/")
def index() : 
    return render_template('posts/index.html')

@bp.route("/categories/")
def categories():
    return render_template('posts/categories.html')

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} {% endblock %} - FlaskApp</title>
    <style>
          h2 {
            width: 100%;
        }

        .title {
            margin: 5px;
            width: 100%;
        }

        .content {
            margin: 5px;
            width: 100%;
            display: flex;
            flex-direction: row;
            flex-wrap: wrap;
        }

        .post {
            flex: 20%;
            padding: 10px;
            margin: 5px;
            background-color: #f3f3f3;
            inline-size: 100%;
        }

        .title a {
            color: #00a36f;
            text-decoration: none;
        }

        nav a {
            color: #d64161;
            font-size: 3em;
            margin-left: 50px;
            text-decoration: none;
        }
    </style>
</head>
<body>
    <nav>
        <a href="{{ url_for('main.index')}}">Flask Applicaton</a>
        <a href="{{ url_for('posts.index')}}">Posts</a>
        <a href="{{ url_for('posts.categories')}}">Categories</a>
        <a href="#">Questions</a>
    </nav>
    <hr/>
    <div class="content">
        {% block content %} {% endblock %}
    </div>

    
</body>
</html>

app/templates/index.html
{% extends 'base.html' %}

{% block content %}
<span class="title">
    <h1>{% block title %} Home Page of FlaskApp {% endblock %}</h1>
</span>
<div class="content">
    <h2>Main flask blue print</h2>
</div> 
{% endblock %}

app/templates/posts/categories.html
{% extends 'base.html' %}

{% block content %}

<span class="title">
    <h1>{% block title %} The Category Page{% endblock %}</h1>
</span>
<div class="content">
    <h2>This is category blue print</h2>
</div> 

{% endblock %} 

app/templates/posts/index.html
{% extends 'base.html' %}

{% block content %}

<span class="title">
    <h1>{% block title %} The Post Page{% endblock %}</h1>
</span>
<div class="content">
    <h2>This is post blue print</h2>
</div> 

{% endblock %}